# Generated by Django 2.0.5 on 2018-06-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0020_add-verbose-name'),
        ('yoga', '0002_auto_20180605_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaLesson',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('lesson_title', models.CharField(max_length=200, null=True)),
                ('lesson_date', models.DateTimeField(blank=True, null=True)),
                ('lesson_level', models.CharField(blank=True, max_length=100, null=True)),
                ('lesson_desc', models.CharField(max_length=500, null=True)),
                ('lesson_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('loc_lat', models.CharField(blank=True, max_length=40, null=True)),
                ('loc_lng', models.CharField(blank=True, max_length=40, null=True)),
                ('lesson_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Yoga Lesson',
            },
            bases=('wagtailcore.page',),
        ),
    ]
