# Generated by Django 2.0.5 on 2018-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_yogalesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogalesson',
            name='loc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
