# Generated by Django 2.0.5 on 2018-06-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('home', '0003_auto_20180604_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_intro',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
