# Generated by Django 2.0.5 on 2018-06-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180605_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
