# Generated by Django 2.0.5 on 2018-06-08 19:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthcategory_healthtreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthindex',
            name='body',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], icon='pilcrow', label='Single Column'))], blank=True),
        ),
    ]
