# Generated by Django 2.0.5 on 2018-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20180608_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtreatment',
            name='treatment_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthtreatment',
            name='treatment_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
